language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t franciscomcg/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true franciscomcg/react-test npm test

after_success:
  - docker build -t franciscomcg/multi-client ./client
  - docker build -t franciscomcg/multi-nginx ./nginx
  - docker build -t franciscomcg/multi-server ./server
  - docker build -t franciscomcg/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push franciscomcg/multi-client
  - docker push franciscomcg/multi-nginx
  - docker push franciscomcg/multi-server
  - docker push franciscomcg/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-273126761811"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
